pub mod about;
pub mod advanced;
pub mod apis;
pub mod appearance;
pub mod component;
pub mod config;
pub mod previews;
pub mod shortcuts;
pub use component::PreferencesComponent;
pub use config::{AppState, CursorShape, ImagePreviewTrigger, SETTINGS_EVENT_BUS, Settings};
