# Stable identity — do not change this value
id = "00000003-0000-4000-8000-000000000003"

name = "kuro"
display_name = "kuro"
color = "#B31825"
duties = "Demonic Arch User, btw"
personality = "Not implemented yet.."
